### ISSUE TITLE
This is not works with aiogram 3

### ISSUE THREAD

**Issue by lev007-ops** [noXplode/aiogram_calendar#5]
This is not works with aiogram 3, how to fix it?

**Comment by noXplode** [comment]
was not using v3 yet, will check this week

**Comment by noXplode** [comment]
checked v3, its not backwards compatible to v2, a lot of changes to classes, both calendars & example must be changed for v3
I`ll create v3 version, but have no estimations when

**Comment by lev007-ops** [comment]
@noXplode, хорошо

**Comment by lev007-ops** [comment]
@noXplode, Okay. I hope it will be fast. It's just that my telegram bot works with your calendar and I transfer it to aiogram 3x

**Comment by lev007-ops** [comment]
@noXplode,Hi. Have you tried transferring it to aiogram 3?

**Comment by o-murphy** [comment]
> @noXplode,Hi. Have you tried transferring it to aiogram 3?

yet I made a fork for aiogram 3
[](https://github.com/o-murphy?tab=repositories)

**Comment by o-murphy** [comment]
> @noXplode, хорошо

You can create another 
branch for aiogram 3 from you master branch and after you can make pull request from my fork, so you'll have versions compatible with aiogram 2 and aiogram 3 in the same time. Also you can clone my repo to your master branch and made validation in you __init__.py file to import required version automaticaly

**Comment by lev007-ops** [comment]
Hello, thanks

**Comment by ZRomik** [comment]
HJello!
Try to use :

@disp.callback_query_handler(simple_cal_callback.filter())
async def process_simple_calendar(query: CallbackQuery, data: dict):
    selected, date = await SimpleCalendar().process_selection(query=query, data=data
    )
    if selected:
        await query.message.answer(
                                   f"Вы выбрали: {date.strftime('%d.%m.%Y')}",
                                   reply_markup=ReplyKeyboardRemove()
                                   )
process_simple_calendar never handle the calendar. What I'm doing wrong?

**Comment by yoworu** [comment]
I also made a fork for aiogram 3.0.0b7 (3.0.0b8)

`pip install aiogram3b8-calendar`

**Comment by noXplode** [comment]
upgraded to aiogram v3, also added some new features - today & cancel button, overridable labels (allows translation to any language)
